# Generated by Django 2.1.7 on 2019-04-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsEquipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='eqpQuantityTaken',
        ),
    ]
