# Generated by Django 2.1.7 on 2019-04-17 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsEquipment', '0002_remove_equipments_eqpquantitytaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='eqpQuantityTaken',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]))]),
        ),
    ]
