# Generated by Django 2.1.5 on 2019-04-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsEquipment', '0002_auto_20190413_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequest',
            name='reqStatus',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'REJECTED'), (3, 'RETURNED')], default=0),
        ),
    ]
